# Generated by Django 3.0.2 on 2020-04-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200125_1617'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
