# Generated by Django 3.0.2 on 2020-01-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20200117_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
