# Generated by Django 3.0.2 on 2020-04-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20200405_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/products/default.png', upload_to='images/products/'),
        ),
    ]
