# Generated by Django 3.0.2 on 2020-01-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, help_text='Defines how much money a student has on his account', max_digits=6),
        ),
    ]
