# Generated by Django 3.0.2 on 2020-03-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20200109_1358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
